version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.13
    working_directory: ~/project/examples/react
    steps:
      - checkout
      - run:
          name: Go to react folder
          command: cd examples/react
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  run-react-ci:
    jobs:
      - build-and-test
